application: twitter-to-sina
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /admin/(.*)
  script: main.py
  login: admin
- url: /(.*)
  script: main.py
